#include "cli/usage.hpp"

#include "config.hpp"

#include <ostream>

namespace atperson {
namespace cli {

void print_usage(std::ostream &out) {
    out << "usage:\n"
        << "  atperson stats\n"
        << "  atperson resources\n"
        << "  atperson neural [status|expand]\n"
        << "  atperson ingest <text> [source-id]\n"
        << "  atperson ingest-file <path> [source-id]\n"
        << "  atperson assoc <token> [limit]\n"
        << "  atperson candidates <context> [limit]\n"
        << "  atperson plans <context> [max-tokens] [beam-width]\n"
        << "  atperson decide <context> [max-tokens] [beam-width] [min-candidate] "
           "[min-support] [max-drop] [max-consecutive]\n"
        << "  atperson audit <context> [max-tokens] [beam-width]\n"
        << "  atperson context <text> [source-id] [author-did]\n"
        << "  atperson familiarity <token>\n"
        << "  atperson drives [max-contexts]\n"
        << "  atperson recall <query> [limit] [min-overlap] [max-prefilter] [on|off]\n"
        << "  atperson groups\n"
        << "  atperson sync [max-pages]\n"
        << "  atperson jetstream [max-events] [max-ms] [--collections <file>] [--dids <file>] [--kinds <file>]\n"
        << "  atperson jetstream status [--collections <file>] [--dids <file>]\n"
        << "  atperson jetstream archive [after-seq] [before-seq] [--span <sequences>] [--collections <file>] [--dids <file>]\n"
        << "  atperson daemon [max-cycles]\n"
        << "  atperson rebuild\n"
        << "  atperson compact\n"
        << "  atperson withdraw <id|source|author> <target>\n"
        << "  atperson cursor [status|reset]\n"
        << "  atperson control <status|pause|resume|writes <on|off>|dry-run <on|off>|"
           "approval <on|off>|approve <digest>|revoke <digest>|shutdown|cancel-shutdown>\n"
        << "  atperson outbound <status [kind]|rules|evaluate <kind> [target] [digest]|"
           "admit <kind> [target] [digest]>\n"
        << "  atperson publish <action-file>\n"
        << "  atperson journal <actions|events|valence [limit]|apply <token> <kind> <signal> <source-id>|\n"
        << "                    map <rule-file>>\n\n"
        << "  atperson protocol [status|resolve <handle>|explain <subject>|oauth-plan <scope>|oauth-metadata <scope>]\n\n"
        << "  atperson autonomy status\n"
        << "environment:\n"
        << "  ATPERSON_TRAINING_HOME    training data directory "
           "(default ~/.ewanc26/atperson/training)\n"
        << "  ATPERSON_STATE            model snapshot path "
           "(default ~/.ewanc26/atperson/training/model.bin)\n"
        << "  ATPERSON_LEDGER           observation ledger path "
           "(default ~/.ewanc26/atperson/training/ledger.bin)\n"
        << "  ATPERSON_INGESTION_STATE  ingestion cursor path "
           "(default ~/.ewanc26/atperson/training/ingestion-state.json)\n"
        << "  ATPERSON_JETSTREAM_STATE  Jetstream cursor path "
           "(default ~/.ewanc26/atperson/training/jetstream-state.json)\n"
        << "  ATPERSON_CONTROL_STATE    operator control path "
           "(default ~/.ewanc26/atperson/control-state.json)\n"
        << "  ATPERSON_OUTBOUND_POLICY  outbound action policy path "
           "(default ~/.ewanc26/atperson/outbound-policy.json)\n"
        << "  ATPERSON_OUTBOUND_BUDGET  outbound rate-budget state path "
           "(default ~/.ewanc26/atperson/outbound-budget.json)\n"
        << "  ATPERSON_OUTBOUND_AUDIT   outbound execution audit log path "
           "(default ~/.ewanc26/atperson/outbound-audit.jsonl)\n"
        << "  ATPERSON_ACTION_JOURNAL   action/outcome journal path "
           "(default ~/.ewanc26/atperson/action-journal.jsonl)\n"
        << "  ATPERSON_PROTOCOL_LEDGER  protocol evidence path "
           "(default ~/.ewanc26/atperson/protocol-evidence.bin)\n"
        << "  ATPERSON_AUTONOMY_RUN_STATE durable lifecycle checkpoint path "
           "(default ~/.ewanc26/atperson/autonomy-run.json)\n"
        << "  ATPERSON_HOME             data directory override "
           "(default ~/.ewanc26/atperson)\n"
        << "  ATPERSON_MEMORY_BUDGET_BYTES   graph growth memory override (default auto)\n"
        << "  ATPERSON_DISK_RESERVE_BYTES    free-space reserve override (default auto)\n"
        << "  ATPERSON_NODE_CAPACITY         graph node ceiling override (default auto)\n"
        << "  ATPERSON_EDGE_CAPACITY         graph edge ceiling override (default auto)\n"
        << "  ATPERSON_NEURAL_CAPACITY       first-generation capacity class / proposal (default auto)\n"
        << "  ATPERSON_NEURAL_EMBEDDING_DIM  first-generation/proposal embedding width\n"
        << "  ATPERSON_NEURAL_HIDDEN_LAYERS  first-generation/proposal hidden-layer count\n"
        << "  ATPERSON_NEURAL_HIDDEN_WIDTHS  colon-separated hidden widths (e.g. 256:128)\n"
        << "  ATPERSON_SYNC_PAGE_SIZE        items per timeline page (default auto)\n"
        << "  ATPERSON_SYNC_MAX_OBSERVATIONS per-run sync observation budget (default auto)\n"
        << "  ATPERSON_SERVICE       PDS/service URL (default https://bsky.social)\n"
        << "  ATPERSON_IDENTIFIER    handle or email for sync/daemon\n"
        << "  ATPERSON_APP_PASSWORD  app password for sync/daemon\n"
        << "  ATPERSON_ALLOW_EXTERNAL_PUBLISHING  explicit network-write master switch\n"
        << "  OAuth integration contract: docs/oauth.md (loopback callback;\n"
           "                           repo scope is explicit; CAR management is separate)\n"
        << "  ATPERSON_SELF_DID      entity DID for unauthenticated Jetstream self-filtering\n"
        << "  ATPERSON_JETSTREAM_ENDPOINT  Jetstream ws(s) URL for public ingestion\n"
        << "                              (default " << kDefaultJetstreamEndpoint << ")\n"
        << "  ATPERSON_JETSTREAM_COLLECTIONS_FILE  one wantedCollections filter per line\n"
        << "  ATPERSON_JETSTREAM_DIDS_FILE         one wantedDids DID per line\n\n"
        << "  ATPERSON_DAEMON_ARCHIVE_AFTER        optional startup archive lower bound\n"
        << "  ATPERSON_DAEMON_ARCHIVE_BEFORE       optional startup archive upper bound\n"
        << "  ATPERSON_JETSTREAM_ARCHIVE_TOKEN     raw token for Jetstream archive replay\n"
        << "  ATPERSON_DAEMON_PAGES_PER_CYCLE  pages per daemon sync cycle (default 1)\n"
        << "  ATPERSON_DAEMON_POLL_MS          wait after an exhausted cycle "
           "(default 300000)\n"
        << "  ATPERSON_DAEMON_CATCHUP_MS       wait while catch-up is pending (default 0)\n"
        << "  ATPERSON_DAEMON_MAX_CYCLES       stop after N cycles (default 0 = unbounded)\n"
        << "  ATPERSON_DAEMON_SNAPSHOT_EVERY   snapshot cadence in cycles (default 1)\n"
        << "  ATPERSON_DAEMON_BACKOFF_INITIAL_MS  first retry delay (default 1000)\n"
        << "  ATPERSON_DAEMON_BACKOFF_MAX_MS      retry delay ceiling (default 300000)\n"
        << "  ATPERSON_DAEMON_BACKOFF_FACTOR      exponential retry factor (default 2.0)\n"
        << "  ATPERSON_DAEMON_BACKOFF_JITTER      jitter fraction in [0,1] (default 0.2)\n\n"
<< "  ATPERSON_TYPESAFE_API_KEY   opt-in key for the advisory `audit` command\n"
         << "  ATPERSON_TYPESAFE_ENDPOINT  advisory audit endpoint "
            "(default https://api.typesafe.ai/v1/systemone)\n"
         << "  ATPERSON_SCHEDULER          autonomous scheduler on/off (default off)\n"
         << "  ATPERSON_SCHEDULER_DRIVES   order scheduler contexts by drives on/off (default off)\n\n"
        << "state-mutating commands (ingest, ingest-file, sync, cursor reset, rebuild,\n"
        << "compact, withdraw, neural expand, daemon, journal apply, journal map) take an exclusive lock on\n"
        << "the data directory;\n"
        << "read-only commands, operator `control` and the `outbound` policy/budget\n"
        << "commands (runtime metadata outside the state set) run without it and see\n"
        << "state as of their read, so a running daemon can still be paused or shut down.\n"
        << "`publish` takes a separate outbound lock, so it never waits on the daemon's\n"
        << "writer lock\n";
}

} // namespace cli
} // namespace atperson
